### ISSUE TITLE
"touchable" option not changing when breakpoint is hit

### ISSUE THREAD

**Issue by dapperdanman1400** [antoniandre/vueper-slides#28]
I have `touchable` set to `false` by default and I only want it to become `true` at the mobile level, so I've set it as an option within a `breakpoints` object, but even when I reach it, the default value still persists.

**Comment by antoniandre** [comment]
Hi @dapperdanman1400,
Thanks for reporting, this is now fixed in version 1.17.3.

**Comment by un-hongly** [comment]
Hi
I'm using vueper-slides 2.10.3 and the issue still exists. please help!

**Comment by antoniandre** [comment]
Hi @un-hongly, thanks for reporting.
This is a regression, it should be fixed in version 2.10.4.

**Comment by un-hongly** [comment]
> Hi @un-hongly, thanks for reporting.
> This is a regression, it should be fixed in version 2.10.4.

It's working.
Thanks :)
